server:
  http_listen_port: 3100
  grpc_listen_port: 0

ingester:
  lifecycler:
    ring:
      replication_factor: 1
  chunk_idle_period: 1h
  chunk_retain_period: 30m
schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: loki_index_
        period: 24h
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks
limits_config:
  retention_period: 168h
