runtime_name: loqa-runtime
environment: development
http:
  bind: 0.0.0.0
  port: 8080
telemetry:
  log_level: info
  otlp_endpoint: ""
bus:
  servers:
    - nats://localhost:4222
  username: ""
  password: ""
  token: ""
  tls_insecure: false
  connect_timeout_ms: 2000
node:
  id: loqa-node-1
  role: runtime
  heartbeat_interval_ms: 2000
  heartbeat_timeout_ms: 6000
  capabilities:
    - name: runtime.core
      tier: balanced
      attributes:
        modality: orchestration
